import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ManagementLayout from "@/components/layout/ManagementLayout";
import { ConfigProvider } from "antd";
import enUS from "antd/locale/en_US";
import thTh from "antd/locale/th_TH";
import "./globals.css";
import theme from "../themeConfig";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CPI Project",
  description: "Generated by create next app",
  icons: "/src/app/favicon.ico",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <ConfigProvider locale={locale === "en" ? enUS : thTh} theme={theme}>
            {children}
          </ConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
